1.1.0

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -151,13 +151,36 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           path: artifacts
-      - name: Move artifacts and index.js to npm directory
+      - name: Create npm folder
+        run: mkdir npm
+
+      - name: Move index.js to npm folder
+        run: mv index.js npm/
+
+      - name: Copy artifacts to npm folder
         run: |
-         run: |
-          # Move index.js
-          mv index.js npm/
-          # Move all artifacts (assuming they are in 'artifacts/' directory)
-          find artifacts/ -type f -exec mv {} npm/ \;
+          if [ -d "artifacts" ]; then
+            cp -R artifacts/* npm/
+          else
+            echo "No artifacts folder found"
+          fi
+
+      - name: Create package.json
+        run: |
+          cat << EOF > npm/package.json
+          {
+          "name": "your-package-name",
+          "version": "1.1.0",
+          "description": "Your package description",
+          "main": "index.js",
+          "scripts": {
+            "test": "echo \"Error: no test specified\" && exit 1"
+          },
+          "keywords": [],
+          "author": "Your Name",
+          "license": "ISC"
+          }
+          EOF
       - name: List packages
         run: ls -R ./npm
         shell: bash
@@ -176,5 +199,5 @@ jobs:
             echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
             npm publish --tag next --access public
           else
-            echo "Not a release, skipping publish" 
+            echo "Not a release, skipping publish"
           fi
